version: '3.1'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: hpai_test
      POSTGRES_USER: hpai
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    ports:
      - 8080:8080